import React, { useState } from 'react';
import { ChevronDown, HelpCircle } from 'lucide-react';

export const FAQ: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      q: 'How does VoiceShield detect AI voice clones and synthetic speech?',
      a: 'VoiceShield uses multi-task acoustic transformers trained on millions of authentic human and synthetic voice samples. It analyzes microscopic acoustic properties like glottal pulse timing, phase alignment, and high-frequency spectral artifacts generated by deep neural text-to-speech models.',
    },
    {
      q: 'Which Indian languages are supported by VoiceShield?',
      a: 'VoiceShield natively supports 12+ Indian regional languages and accents, including Hindi, Tamil, Telugu, Bengali, Kannada, Marathi, Gujarati, Malayalam, Punjabi, Odia, Assamese, and Indian English.',
    },
    {
      q: 'Is my audio uploaded or stored on permanent servers?',
      a: 'No. By default, VoiceShield offers an ephemeral zero-retention mode. Audio payloads are analyzed entirely in volatile RAM during inference and purged immediately post-analysis.',
    },
    {
      q: 'Can VoiceShield be integrated into existing call center or telephony software?',
      a: 'Yes! VoiceShield provides low-latency REST and WebRTC WebSocket APIs with sub-200ms inference time, suitable for live telephony monitoring, Video KYC, and banking IVR channels.',
    },
    {
      q: 'Is signup required to check a voice on the platform?',
      a: 'No signup is required for basic voice verification previews. Enterprise users and developers can register for API key access.',
    },
  ];

  return (
    <section className="py-20 bg-slate-50/50 border-b border-slate-200/60">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header */}
        <div className="text-center max-w-2xl mx-auto mb-14">
          <div className="inline-flex items-center space-x-1.5 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-bold border border-blue-200/60 mb-2">
            <HelpCircle className="w-3.5 h-3.5" />
            <span>Frequently Asked Questions</span>
          </div>
          <h2 className="text-3xl font-extrabold text-slate-900 tracking-tight">
            Got Questions? We Have Answers.
          </h2>
        </div>

        {/* Accordion */}
        <div className="space-y-3">
          {faqs.map((faq, idx) => {
            const isOpen = openIndex === idx;
            return (
              <div
                key={idx}
                className="bg-white rounded-2xl border border-slate-200/80 shadow-2xs overflow-hidden transition-all"
              >
                <button
                  onClick={() => setOpenIndex(isOpen ? null : idx)}
                  className="w-full text-left p-5 flex items-center justify-between font-bold text-slate-900 text-sm hover:text-blue-600 transition-colors"
                >
                  <span>{faq.q}</span>
                  <ChevronDown className={`w-4 h-4 text-slate-400 transition-transform duration-200 shrink-0 ml-3 ${isOpen ? 'rotate-180 text-blue-600' : ''}`} />
                </button>

                {isOpen && (
                  <div className="px-5 pb-5 text-xs text-slate-600 leading-relaxed font-normal border-t border-slate-100 pt-3">
                    {faq.a}
                  </div>
                )}
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
};
